### ISSUE TITLE
Feature: Call For Help (CFH)

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#101]

**Comment by emansom** [comment]
@Raptosaur is working on this in his Kepler fork on the `develop` branch.

**Comment by Raptosaur** [comment]
![screenshot_4](https://user-images.githubusercontent.com/7223575/43356269-d15bd1c8-925c-11e8-8aa5-3231737de19d.png)
![screenshot_3](https://user-images.githubusercontent.com/7223575/43356270-d18a4f1c-925c-11e8-96bd-f1a96ba51f58.png)

Picking up CFH works. Need to find out why the client is interpreting the Room ID wrong, and implement the "Pick up & Reply".

**Comment by Raptosaur** [comment]
Need to make it so that if call isn't picked up it shows <nobody> I think that this is how it worked back in the day, from what I can find.
![silly_hobba_calls](https://user-images.githubusercontent.com/7223575/43356885-63bb291e-9268-11e8-9eef-ef780fea8481.gif)

**Comment by Raptosaur** [comment]
Current progress: https://www.screencast.com/t/De6ctNvX
Everything is working well so far. Only things left to implement is the escalation and de-escalation of CFH and the Delete open CFH.

**Comment by Quackster** [comment]
I didn't close it...? It's still not complete, but the source changes have been merged.
