### ISSUE TITLE
Feature: Camera (Shockwave MultiUser protocol)

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#103]

**Comment by Quackster** [comment]
I'm not going to post issues for features that I'm unsure I'll be able to do.

**Comment by Quackster** [comment]
Adding these comments here for reference so I don't need to search for them again:

http://opensmus.sourceforge.net/

https://forums.adobe.com/thread/1499539 (all the links are dead here but it works on archive.org)

**Comment by Quackster** [comment]
Camera has been added (and works)! 🙌 

But there's two things I need to do before I mark this as completed:

- Stop a person from using a drink machine when holding a camera.
- Make the person play the "use item" animation when taking a photo.

**Comment by Quackster** [comment]
Feature has been completed.
