### ISSUE TITLE
:pickall deletes all items except post-it's

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#111]

**Comment by Quackster** [comment]
Fixed: https://github.com/Quackster/Kepler/commit/c36c42f31fab73d4f4534f8ae34cfc358ad0413f

**Comment by Quackster** [comment]
Keep post-its in room instead: https://github.com/Quackster/Kepler/commit/39fd7ba12000550a9cb350b5bb6943fe6cc4136e
