### ISSUE TITLE
Feature: furniture history/rollback system to combat scamming

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#119]

**Comment by Quackster** [comment]
Habbo didn't have this feature, so neither should Kepler. https://help.habbo.com/hc/en-us/articles/221642248-All-about-Scamming

>Habbo cannot take responsibility for user-error and so we are unable to return the furniture or credits to the user in this case.

**Comment by emansom** [comment]
Only because Sulake didn't put the engineering resources into bettering the situation of users being scammed; shouldn't mean Kepler should follow the same mistakes.

**Comment by Quackster** [comment]
I disagree, I'm not going to take responsibility for other users' actions.
