### ISSUE TITLE
Can move to tiles that are already occupied

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#128]
[![Video showing the bug](https://images.oldhabbo.com/validtile-bug-preview.png)](https://images.oldhabbo.com/validtile-bug.mp4)

[![Second video showing the bug](https://images.oldhabbo.com/validtile-bug2-preview.png)](https://images.oldhabbo.com/validtile-bug2.mp4)

**Comment by Quackster** [comment]
Issue fixed: https://github.com/Quackster/Kepler/commit/4fcadbf06e06c26120b3f5e81c5975e211a2666b
