### ISSUE TITLE
Limit packet rate per IP

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#134]
To mitigate potential DoS

**Comment by emansom** [comment]
Needs security label

**Comment by Quackster** [comment]
Added: https://github.com/Quackster/Kepler/commit/22ae54675723694dbd1cac8cb7d3931863ddff9b

I've set it to 2048 KB/s but I feel like that's probably just a little bit too generous.

**Comment by emansom** [comment]
Isn't that 2KB?

**Comment by Quackster** [comment]
No, it's bytes/second, see here: https://netty.io/4.0/api/io/netty/handler/traffic/ChannelTrafficShapingHandler.html#ChannelTrafficShapingHandler-long-long-

>Parameters:
>writeLimit - 0 or a limit in bytes/s
>readLimit - 0 or a limit in bytes/s

**Comment by emansom** [comment]
I reckon that ought to be enough.

**Comment by Quackster** [comment]
Then do that then? This is your issue you opened up, after all.

**Comment by Quackster** [comment]
Added: https://github.com/Quackster/Kepler/commit/db34c88bab411e2a1f84028d891a71f49db41ad7

See: https://github.com/Quackster/Kepler/issues/135#issuecomment-412315983
