### ISSUE TITLE
Mitigate Slowloris attack

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#135]
The [Slowloris attack](https://en.wikipedia.org/wiki/Slowloris_(computer_security)) in FUSE v0.2.0 protocol terms effectively means sending and responding to ping and maybe logging in, but not doing much else. And then opening many many connections like that, effectively starving the physical server's resources.

We need a way to detect this effectively without false positives.

**Comment by Quackster** [comment]
Could this be mitigated by having a configurable amount of connections per IP address?

**Comment by emansom** [comment]
That would solve part of the problem. But not quite, as you still can keep a connection alive while doing the bare mimimum of activity.

Limiting connections per IP is a good practice, but won't stop a distributed Slowloris attack

**Comment by Quackster** [comment]
Mitigation are done by adding bandwidth limiting and max connections for IP settings.

https://github.com/Quackster/Kepler/issues/134

https://github.com/Quackster/Kepler/issues/133

**Comment by emansom** [comment]
A distrbuted Slowloris attack would still be possible. I suggest killing the connection if a TRY_LOGIN or SSO doesn't succeed in five seconds.
