### ISSUE TITLE
Refresh console friend list when friend goes offline or enters room

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#136]
As the cache/refresh implementation the client has for the console is deeply flawed, and this would bypass/mitigate that.

**Comment by Quackster** [comment]
The console already refreshes automatically, the client requests it.

**Comment by emansom** [comment]
Yeah, and multiple times that results in stale or really out-of-date data. The client refresh implementation is flawed.

**Comment by Quackster** [comment]
Fixed with commit: https://github.com/Quackster/Kepler/commit/33bb4ca92271e1f072b7aa92ac010d7841423351
