### ISSUE TITLE
Roller dont sit the players on chairs

### ISSUE THREAD

**Issue by Sefhriloff** [Quackster/Kepler#138]
![imagem](https://user-images.githubusercontent.com/41347100/43040790-d3e3730a-8d44-11e8-9e82-b5a3e3cd6759.png)

**Comment by Sefhriloff** [comment]
Sometimes can have 2 players on same square

**Comment by Quackster** [comment]
Fixed with commit: https://github.com/Quackster/Kepler/commit/d5b94578023c1ba281a1fe19e20d22a72fde5747
