### ISSUE TITLE
Can't place rollers on rugs

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#139]

**Comment by Sefhriloff** [comment]
isnt a bug on original habbo you cant put a roller on rugs xD

**Comment by emansom** [comment]
Not sure if this is a bug tho, like @Sefhriloff said.

**Comment by Quackster** [comment]
Testing on Habbo then, I suppose I should have in the first place.

**Comment by Quackster** [comment]
Tested on Habbo, you can't place rollers on rugs... but I disagree with that. What kind of stupid person doesn't allow rollers on rugs? 🙄
