### ISSUE TITLE
I can't connect to Kepler.

### ISSUE THREAD

**Issue by fraahk** [Quackster/Kepler#14]
![image](https://user-images.githubusercontent.com/62943069/78028280-09b27880-735f-11ea-9ab1-6b3a58563270.png)
![image](https://user-images.githubusercontent.com/62943069/78028293-13d47700-735f-11ea-8279-f0010e8d089e.png)
I think i've setted up everything okay, but when i try to open the client, this happens. Any ideas?

**Comment by fraahk** [comment]
I found out that it's an issue with my loader that doesn't have the required sso login for v21, so i dont really know if it's an issue anymore, where can i find a working loader?

**Comment by Webbanditten** [comment]
This sometimes happens when the client expect another server version. Try playing with the different versions available in the server.ini file.

**Comment by fraahk** [comment]
> This sometimes happens when the client expect another server version. Try playing with the different versions available in the server.ini file.

Okay! I'll try that, give me a second.

**Comment by fraahk** [comment]
Didn't worked. I guess there's something wrong with the loader, im not using a cms.

**Comment by Quackster** [comment]
The server is closing your connection because it requires an SSO ticket and you're giving an invalid one.

This isn't an issue with the server itself, closing the issue.
