### ISSUE TITLE
Show peak users online in last 24h in both :status and :whosonline

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#145]

**Comment by Quackster** [comment]
Added:

https://github.com/Quackster/Kepler/commit/ecdaeffa7f8ff48ba04a97aac4e4d17b49137c03

https://github.com/Quackster/Kepler/commit/022d812307c2e237c2b15fb404f7673e3238c404

**Comment by Quackster** [comment]
Closed, assuming the feature is working.
