### ISSUE TITLE
Global credits handout cycle should be user-timestamp based instead of globally

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#147]
Now a user can register, and with a bit of luck, after two minutes, he'll receive a defined credit amount.
It should however account the timestamp the user last received a credit handout via the global handout cycle.
I propose after logging in and setting `last_online`, applying `last_online` to an internal `lastHandout`.
This `lastHandout` can then be used in the same global handout cycle.

**Comment by Quackster** [comment]
Added: https://github.com/Quackster/Kepler/commit/b4b40038faa281a8936e92b11a8ac65bb3193db9
