### ISSUE TITLE
Global credits handout cycle should batch update queries in one transaction

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#149]
Currently the global credits handout cycle sends update queries on iterating over a user, each time blocking the database connection for a while. This could potentially introduce lagg when lots of players are online.

Using one transaction for all the update credits queries would mitigate this potential lagg.

I suggest adding a `increaseCreditsBatch(Map<PlayerDetails, int amount> list)` function to `CurrencyDao` to implement this need.

**Comment by Quackster** [comment]
This cannot work if (https://github.com/Quackster/Kepler/issues/149) is implemented.
