### ISSUE TITLE
Use JDBI instead of raw JDBC for more readable DAO code

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#150]
[JDBI](http://jdbi.org/) is a wrapper around [JDBC](https://en.wikipedia.org/wiki/Java_Database_Connectivity) that makes working with [JDBC](https://en.wikipedia.org/wiki/Java_Database_Connectivity) less of a pain in the ass.

**Comment by emansom** [comment]
[Trove](https://github.com/jaytreebeard/Trove) uses the [JDBI](http://jdbi.org/) library, example code of their usage can be found [here](https://github.com/jaytreebeard/Trove/blob/master/src/main/java/com/trove/database/dao/UserDAO.java), [here](https://github.com/jaytreebeard/Trove/blob/master/src/main/java/com/trove/database/dao/GameServerDAO.java) and [here](https://github.com/jaytreebeard/Trove/blob/master/src/main/java/com/trove/database/dao/ConfigDAO.java). Also [here](https://github.com/jaytreebeard/Trove/blob/master/src/main/java/com/trove/database/dao/managers/RankManagerDAO.java).

**Comment by Quackster** [comment]
Not an issue.
