### ISSUE TITLE
Pathfinder breaks randomly

### ISSUE THREAD

**Issue by Raptosaur** [Quackster/Kepler#153]
## Issue
Path finder decides to stop letting you move around randomly.

### Steps to reproduce
* Unknown

### Expected response
Be able to walk around in free spaces

### Additional Information
In my room (Fan-site drop in) we were trying to walk around, but couldn't. We removed the stacked teleporter to ensure that this was not the issue, as well as the rugs. It was also dependant on at what position you entered the room. For example, Me and Alito both managed to enter but then @emansom tried and was completely unable to move whilst both Alito and myself were limited in our ability to move around the room.

**Comment by Quackster** [comment]
Looks like it's been fixed with the latest commits. Closing issue.

(btw I appreciate the time you took to write this issue ❤️ )
