### ISSUE TITLE
stacking issues certain furniture/rotating objects

### ISSUE THREAD

**Issue by hormelomone** [Quackster/Kepler#157]
There are still some problems with stacking particular furniture like Chinese tables and perhaps others that might need testing. Also rotating objects while stacking doesn't seem to work.

Thanks, hormel

**Comment by Quackster** [comment]
>There are still some problems with stacking particular furniture like Chinese tables and perhaps others that might need testing.

What problems? How about you give me more information?

**Comment by Quackster** [comment]
Issue closed because lack of information.
