### ISSUE TITLE
Catalogue 2 issues

### ISSUE THREAD

**Issue by JairKuma** [Quackster/Kepler#159]
''Plasto'' category is empty and in Category ''Gallery'' teaser missing image catalog_gallery_teaser1_en in c_images/catalogue/

Here the image for fix
![catalog_gallery_teaser1_en](https://user-images.githubusercontent.com/23510300/43420759-50c55b72-9434-11e8-9d1d-c88b47e58cd7.gif)

**Comment by Quackster** [comment]
Plasto issue is known, and thanks for the image.
