### ISSUE TITLE
Chat bubbles need a server timeout

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#161]
As the client sometimes doesn't send `USER_CANCEL_TYPING`. I suggest a configurable amount via GameConfiguration that defaults to either 10 or 15 seconds (needs some testing)

**Comment by Quackster** [comment]
Added: https://github.com/Quackster/Kepler/commit/537a43d1921e6cf3c68979b83c3d3f8f1aa636bc

Needs testing to see what's the perfect chat bubble timeout, though.
