### ISSUE TITLE
Lido queue behavior is different from Habbo

### ISSUE THREAD

**Issue by rafaeldamasceno** [Quackster/Kepler#163]
The only video which seems to be recorded from actual Habbo that shows the interactions I'm about to talk about is this one: https://www.youtube.com/watch?v=bvcv_hWhJOQ

Kepler currently does it like this: if you own tickets, no matter what queue tile you press, you go to the end of the queue; if you don't own tickets, you can't press any queue tile.

The actual behavior should be something like this: no matter what tile you press, just let the pathfinder do its job (the behavior should mimic a set of rollers in the same position as the queue tiles; you can cut in front of others, you can enter in any non-blocked tile); however, if you don't own tickets, you are pushed out of the queue to an adjacent non-queue tile, and the ticket window is opened. This behavior can be seen at 2:27 in the linked video.

**Comment by Quackster** [comment]
Adjusted:

https://github.com/Quackster/Kepler/commit/44df3178cc72110250ed30af223805267760ce41

https://github.com/Quackster/Kepler/commit/491c3f4f73bf012f03ab5a3c0eec0218875454ea

This should be tested to confirm it works as expected. 😄

**Comment by rafaeldamasceno** [comment]
After a0a20215c6f2f0057df4f98859fb18dd685c133e, I feel like the behavior is really close to Habbo's.

Two notes on the displacement behavior (which I should've made clearer beforehand): 
- The Habbo should be teleported. It shouldn't walk.
- I can't recall what was the algorithm for choosing the tile to be displaced to. It makes sense for it to be the tile you came from before stepping on the queue, but I feel that wasn't the case. However, as in no video people enter the queue from the top, I can't confirm it.

Two more things which I can't recall or confirm via YouTube videos, so I'd really appreciate if someone thought about this to see if they remember it better than I do:
- Queue tiles being ignored by pathfinder. It feels wrong that people cut the queue in the following example. I think that what happened is that queue tiles were ignored by the pathfinder unless they were the destination tile. A certain public hotel with Lido does it like this, which positively confirms my memory of it.
![](https://i.imgur.com/SUhH0ub.png)
- Being able to leave the queue. I have absolutely no idea whether or not you could just walk off the queue. I'm leaning to not, but this definitely needs verification.

**Comment by Quackster** [comment]
>The Habbo should be teleported. It shouldn't walk.

Yes, correct, the Habbo should not walk (oops!).

>I can't recall what was the algorithm for choosing the tile to be displaced to. It makes sense for it to be the tile you came from before stepping on the queue, but I feel that wasn't the case. However, as in no video people enter the queue from the top, I can't confirm it.

The code checks checks the square in front, then checks right side, then checks left side, then checks behind you, in that order of checking (as shown below):

https://github.com/Quackster/Kepler/blob/master/Kepler-Server/src/main/java/org/alexdev/kepler/game/triggers/furniture/PoolQueueTrigger.java#L29

So no, the code doesn't always check behind the user, but as you can see here: https://youtu.be/bvcv_hWhJOQ?t=147

The girl walking on the tile gets teleported to the tile she was just on. 

>Queue tiles being ignored by pathfinder. It feels wrong that people cut the queue in the following example. I think that what happened is that queue tiles were ignored by the pathfinder unless they were the destination tile. A certain public hotel with Lido does it like this, which positively confirms my memory of it.

**Comment by rafaeldamasceno** [comment]
>The code checks checks the square in front, then checks right side, then checks left side, then checks behind you, in that order of checking (as shown below)

But that directly conflicts with Habbo's official behavior in https://youtu.be/bvcv_hWhJOQ?t=147. Take the following image into consideration. What I meant with not being able to confirm anything is that we never see people stepping in red from blue. We do see people stepping in red from green, and they're pushed back to green. Kepler pushes these people to blue, though.
![](https://i.imgur.com/zwOtTx9.png)

As for the pathfinder part, I've already clarified with you. [This](https://gfycat.com/MindlessFatAcornwoodpecker) is what currently happens in Kepler, and [this](https://gfycat.com/ElaborateUntimelyHoverfly) is what happens in the other hotel. I think the latter is what actually happened in Habbo (not talking about the exact pathing, just the going around part).
