### ISSUE TITLE
Lido can't change room in water

### ISSUE THREAD

**Issue by GuenosNoLife** [Quackster/Kepler#170]
In water we can't switch Lido 1 to Lido 2, reverse same issue.
But in normal condition It's work.

![enregist _2018_08_05_12_21_42_662](https://user-images.githubusercontent.com/42077840/43684952-441d43d8-98aa-11e8-9d3e-041de02044d3.gif)
![enregist _2018_08_05_12_20_49_415](https://user-images.githubusercontent.com/42077840/43684953-47cb6a64-98aa-11e8-9fb1-0522b44d9924.gif) #

**Comment by Quackster** [comment]
Added. 😅 

![2018-08-16_23-02-101 1](https://user-images.githubusercontent.com/1328523/44238019-394a5680-a1f6-11e8-82f1-59be7cb79a5c.gif)
