### ISSUE TITLE
Bug in Rooftop

### ISSUE THREAD

**Issue by JairKuma** [Quackster/Kepler#171]
The bug is when someone returns from rooftop 2 and if there is someone at the door of rooftop you can not move until he moves, also there are some seats where I can not sit on a rooftop
![dibujo](https://user-images.githubusercontent.com/23510300/43793935-71a7bcd4-9a6c-11e8-9003-43488fad1c33.png)
![dibujo](https://user-images.githubusercontent.com/23510300/43794182-094a3dbe-9a6d-11e8-94a5-97eee7f47b3b.png)

**Comment by Quackster** [comment]
Should be fixed completely, please test to confirm. Patch should already be live on oldHabbo.

**Comment by emansom** [comment]
Is live, yes, all chairs work now :)
