### ISSUE TITLE
Ask for confirmation via poll packets when using :pickall

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#172]
Currently when using `:pickall` it immidiately picks up all room items, without asking for confirmation first. This results in some gullible users being able to be tricked into destroying their own rooms.

Using a poll window for confirmation could mitigate this. Puomi also uses poll packets for some commands (primarily stock trading).

**Comment by Quackster** [comment]
There's no confirmation packet in v21 (there is in flash though). Habbo during shockwave didn't have confirmation at all with the ``pickall`` command, as you can see here: https://youtu.be/mybctlnerZQ?t=88

So I won't be adding it. I want to stick to how it was originally.
