### ISSUE TITLE
Teleport broken can't back if blocked

### ISSUE THREAD

**Issue by GuenosNoLife** [Quackster/Kepler#173]
![enregist _2018_08_08_11_42_56_432](https://user-images.githubusercontent.com/42077840/43829874-54f52e7a-9b00-11e8-8703-3b209d13a908.gif)

**Comment by Quackster** [comment]
Yeah I know what I did which broke it. It was this commit (https://github.com/Quackster/Kepler/commit/58a2eb4d54fa1489f2493a0767011baf7e6ac5f2) which was associated with trying to fix when a user lands into another user when crossing between public room walkways and the first user could no walk.

So I removed that change and added this:

https://github.com/Quackster/Kepler/commit/4722c56b74874b1d2f03bb9273f9876f2ca318dc

https://github.com/Quackster/Kepler/commit/78614228a6a3e4c50b5d01dd2573ac054ae0ba40

Please let me know it's been fixed on, http://kepler.alex-dev.org/ as that's my my test hotel.

**Comment by Quackster** [comment]
Fixed: https://github.com/Quackster/Kepler/commit/67ded16ec7d2f1e84ae215ef0cfc7d381582be59
