### ISSUE TITLE
Somes badge(s) are bad

### ISSUE THREAD

**Issue by GuenosNoLife** [Quackster/Kepler#174]
I don't know if It's just one or lot but SGR have bad shower background is pink, should be white for transparent (because v21 is white, If I'm right) and It's not center.

![enregist _2018_08_08_12_04_32_271](https://user-images.githubusercontent.com/42077840/43831201-a5490358-9b03-11e8-9104-3d37edf9e761.gif)

**Comment by emansom** [comment]
This is an client issue. Not a server/Kepler issue.

**Comment by JairKuma** [comment]
The palette image is not totally white for default, use my fix badge
