### ISSUE TITLE
Public Rooms Bugs

### ISSUE THREAD

**Issue by JairKuma** [Quackster/Kepler#187]
Library: Walkable lights and table 
![library lights and table](https://user-images.githubusercontent.com/23510300/43997908-b8774840-9dd8-11e8-99a9-4e2233234ce7.png)
Tv Studio: Chairs top
![tv studio bad top chairs](https://user-images.githubusercontent.com/23510300/43997912-d70de976-9dd8-11e8-816f-3ca6fa074ea1.png)
Power Gym: Walkable wall of notes
![power gym wall of notes walkable](https://user-images.githubusercontent.com/23510300/43997915-e84eb9ae-9dd8-11e8-90d4-72f2ed11df2c.png)
Beauty Salon: Missing magic tiles, some chairs not work and missing beauty salon 2
![beauty salon chairs and magic tile](https://user-images.githubusercontent.com/23510300/43997919-ff1ab2be-9dd8-11e8-8141-5ca5b9705d8f.png)
The Den: Walkable tables 
![the den tables](https://user-images.githubusercontent.com/23510300/43997921-0af9fe1e-9dd9-11e8-829d-61d94bce576f.png)
The Dirty Duck Pub: Bot bar and Chairs top
![the dirty duck pub bot bar and chairs bad top](https://user-images.githubusercontent.com/23510300/43997924-1b8baac0-9dd9-11e8-862a-4d096ffd2469.png)
Cafe Ole: Tables
![cafe ole](https://user-images.githubusercontent.com/23510300/43997934-7713e4ca-9dd9-11e8-9a9e-84b66b3d16a5.png)
Space Cafe: Animation lights and poster
![space cafe animations light poster](https://user-images.githubusercontent.com/23510300/43997961-140817ba-9dda-11e8-82dc-a34cd93b7f06.png)
Oriental Tearoom: Tables
![oriental tea room tables](https://user-images.githubusercontent.com/23510300/43997964-2b069e46-9dda-11e8-985f-5f87391a30d3.png)
The Chromide Club: Tables and Heightmap
![the chromide club tables heightmap](https://user-images.githubusercontent.com/23510300/43997972-70c3e0ba-9dda-11e8-9b5e-c272d133536c.png)
Club Massiva II: Room 2 dj table (wall walkable?)
![club massiva wall walkable dj table](https://user-images.githubusercontent.com/23510300/43997976-7e13a2a0-9dda-11e8-90b0-cbb76c2ac1a1.png)
Club Mammoth: Upstairs sofas not work
![club mammoth sofas not sit](https://user-images.githubusercontent.com/23510300/43997982-8f0e0384-9dda-11e8-8876-7439456fa9d6.png)
Gate Park: Missing Magictiles, banks not work
![gate park magic tiles chairs](https://user-images.githubusercontent.com/23510300/43997985-9f2b6a04-9dda-11e8-9daf-3b7eafa1c7a3.png)
The Park: Missing Magictiles
![infobus](https://user-images.githubusercontent.com/23510300/43997994-b655c65c-9dda-11e8-8c94-6919823de132.png)
Lido: Window and Vote system
![dibujo](https://user-images.githubusercontent.com/23510300/43997995-c4e7844e-9dda-11e8-8756-f95ed3360371.png)
Rooftop Rumble: Pool and Window 
![wobble squabble](https://user-images.githubusercontent.com/23510300/43997997-d5261082-9dda-11e8-8a8f-9c92cd4772c2.png)
Poker Room: Walkable Lights
![poker room](https://user-images.githubusercontent.com/23510300/43998001-e59558ba-9dda-11e8-89c7-331e04d4077b.png)

**Comment by Quackster** [comment]
Two of your issues are duplicates:

(Lido: Window and Vote system)

https://github.com/Quackster/Kepler/issues/87

https://github.com/Quackster/Kepler/issues/86

And missing magic tiles aren't considered bugs.
