### ISSUE TITLE
People with rights should be able to enter rooms with doorbell

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#199]

**Comment by Quackster** [comment]
Did you test this behavior exist on Habbo offically?

**Comment by rafaeldamasceno** [comment]
I just confirmed that this is not how it works on official Habbo.

**Comment by Raptosaur** [comment]
If I remember correctly - a user with rights could go in, they just couldn't if it was password protected.

I think that they changed this in newer versions to allow users who are admins in the room's group. I could be wrong though.

**Comment by Quackster** [comment]
@rafaeldamasceno 

Do you mean current Kepler behaviour or the proposed change?

**Comment by rafaeldamasceno** [comment]
@Quackster I mean the proposed change. However, @Raptosaur might be right about this having changed as of recently, and that would mean that the proposed change is, in fact, appropriate. I can't add to the discussion anymore as I simply can't remember how it worked.

**Comment by Quackster** [comment]
If it's changed recently (ie, in flash only) then it doesn't belong in Kepler, because Habbo hasn't been v21 for a long time, and I'm emulating from that version, not current Habbo.

**Comment by Quackster** [comment]
It's settled. I'm not adding it, from @Raptosaur's comment:

![image](https://user-images.githubusercontent.com/1328523/44416769-30bb9c80-a5b7-11e8-9b0d-546b80a29e27.png)

**Comment by Quackster** [comment]
Added: https://github.com/Quackster/Kepler/commit/fc7a09c66d8c12230376d01be70de7915f48f060

Needs testing.
