### ISSUE TITLE
Shockwave question

### ISSUE THREAD

**Issue by ssl** [Quackster/Kepler#2]
Hi,

I did my setup and found out Shockwave is end of life and not supported in the latests browsers. I was wondering; wat is the best method to actually play on it?

Thanks!

**Comment by emansom** [comment]
Shockwave is supported on a Windows platform using browsers that support NP-API. [Pale Moon](https://www.palemoon.org/) is recommended, as it's an Firefox fork which guarantees NP-API compatibility far into the future. One of the only projects in that scope that's still being maintained.

32-bit installation of Pale Moon is required to mitigate Shockwave compatibility issues.

**Comment by ssl** [comment]
Thanks! Is there any NP-API supported browser for Mac?

**Comment by emansom** [comment]
You could try running Pale Moon via Wine. Should be installable via `brew`. Make sure to tell Wine you want to emulate an 32-bit environment via the environment setting `WINEARCH=win32`.
