### ISSUE TITLE
Can't enter password protected room across teleports and moving blocked

### ISSUE THREAD

**Issue by GuenosNoLife** [Quackster/Kepler#201]
All explain at gif.

![enregist _2018_08_19_21_32_44_546](https://user-images.githubusercontent.com/42077840/44312418-f0fa8680-a3f7-11e8-9c70-4a63869a5063.gif)

**Comment by Quackster** [comment]
Should be fixed with this commit: https://github.com/Quackster/Kepler/commit/944a14c3ab88eb50b3c0c110fb70ea3580275fde

**Comment by GuenosNoLife** [comment]
Fixed.
