### ISSUE TITLE
Open teleport

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#203]
Sometimes a teleport stays open, even when reloading the room, as seen in this room with lots of teles on rollers.

![afbeelding](https://user-images.githubusercontent.com/42554575/44365030-e3f99800-a4c8-11e8-9868-8689afd2aea7.png)

**Comment by Quackster** [comment]
Should be fixed after this commit: https://github.com/Quackster/Kepler/commit/388039069aeb859aa88741ef93c9988b54086db2

**Comment by Sefhriloff** [comment]
The same appen on original habbo zz

**Comment by Sefhriloff** [comment]
![ezgif-3-f3927bd115](https://user-images.githubusercontent.com/41347100/44417377-e0b3ea00-a564-11e8-8756-d2d4610c06e5.gif)

**Comment by Quackster** [comment]
Yeah but the bug is cancerous so I'll try to mitigate it as much as I can. 🙂
