### ISSUE TITLE
Cannot create certain room

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#204]
I cannot create a room with 80 tiles.

![afbeelding](https://user-images.githubusercontent.com/42554575/44365076-fffd3980-a4c8-11e8-8f39-7ef8e5d539e9.png)

EDIT: when I'm HC it works! So it's a little bug.

**Comment by GuenosNoLife** [comment]
No problem, you need reload the client and fixed.

It's bug from shockwave player, sometime I can't roll the dice and when I restart client, fixed.

**Comment by gefliptemens** [comment]
No, it's not fixed even after reloading serveral times.

**Comment by GuenosNoLife** [comment]
Works if you are a HABBO Club member... This room is not HC.

**Comment by Quackster** [comment]
Fixed. https://github.com/Quackster/Kepler/commit/6f50e02d41e0167ba8b58eaa6cb5082d5adfbebb
