### ISSUE TITLE
Messenger go to the same room bug

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#205]
When I click on "go to the same room" for a **public** room, nothing happens. Normal rooms work fine.

**Comment by Quackster** [comment]
Yeah I don't know how to fix this.

**Comment by Quackster** [comment]
Should be fixed: https://github.com/Quackster/Kepler/commit/b3be9611c9ee0bd9814c9f19a548c89138520404

Don't ask me why the +1000 is needed, but it works, and I saw in other databases (Holograph, Woodpecker etc) that 1000 offset was required for public rooms, weird.
