### ISSUE TITLE
Doors on rollers

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#207]
I checked it again on real Habbo, and indeed it should be impossible to put doors on rollers.

![afbeelding](https://user-images.githubusercontent.com/42554575/44368671-e6152400-a4d3-11e8-97f8-fb377e8a9409.png)

**Comment by Quackster** [comment]
Added: https://github.com/Quackster/Kepler/commit/87a0bdc6d3b849b3c628552ab67cf0fceb982508
