### ISSUE TITLE
Sittable items don't block the pathfinder diagonally

### ISSUE THREAD

**Issue by rafaeldamasceno** [Quackster/Kepler#208]
[Habbo's behavior](https://gfycat.com/HeavenlySoreGangesdolphin) vs. [Kepler's behavior](https://gfycat.com/RectangularBlaringDassie)

**Comment by Quackster** [comment]
Fixed. https://github.com/Quackster/Kepler/commit/04e4a07940f6ef7cf380f3a3bd16a323cb370eae
