### ISSUE TITLE
Teleporters don't check for user inside

### ISSUE THREAD

**Issue by rafaeldamasceno** [Quackster/Kepler#209]
This currently allows a lot of buggy behavior. Just try and double click the teleporter as you're exiting it. [Here](https://gfycat.com/UnacceptableMadGibbon)'s an example.

**Comment by Quackster** [comment]
Don't double click them then?

**Comment by emansom** [comment]
Kepler should only allow one task per teleport set at a time.

**Comment by Quackster** [comment]
Can't reproduce it after changing the behaviour: https://github.com/Quackster/Kepler/commit/e8d975480c6b8a7062a9469a666dc2a8e066cd19

**Comment by rafaeldamasceno** [comment]
@Quackster Very funny 😛 I only reported because I can't reproduce this in Habbo. In any case, I can still reproduce it after e8d975480c6b8a7062a9469a666dc2a8e066cd19.

**Comment by Quackster** [comment]
@rafaeldamasceno Did you realise that oldHabbo hasn't been updated yet? 🙄

**Comment by rafaeldamasceno** [comment]
@Quackster I run my own local testing environment. I can record it again with a full git pull + git status + build sequence, but I thought you'd find that boring.

**Comment by Quackster** [comment]
Well you've obviously not pulled the updates because I cannot reproduce it.

![](https://i.imgur.com/9WNUPgc.gif)

**Comment by Quackster** [comment]
Teleporters should be near flawless now, please pull from master when you can.

**Comment by emansom** [comment]
Spam clicking teleporters next to eachother reproduces the issue.

**Comment by rafaeldamasceno** [comment]
As @emansom said, it's still reproducible, albeit harder to do so.

**Comment by Quackster** [comment]
The issue is this line: https://github.com/Quackster/Kepler/blob/master/Kepler-Server/src/main/java/org/alexdev/kepler/messages/incoming/rooms/teleporter/GETDOORFLAT.java#L41

Because GETDOORFLAT gets called too early before the user is even inside the teleporter yet. I'll fix it when I'm home.
