### ISSUE TITLE
Feature: Who's in here?

### ISSUE THREAD

**Issue by rafaeldamasceno** [Quackster/Kepler#211]
Described in http://www.habborator.org/tips/index.html, in the tricks of the past section.

Holding down the SHIFT key while clicking on the “Go” field of public spaces lists users like so:

![](http://www.habborator.org/tips/gfx/who.gif)

**Comment by Quackster** [comment]
Added.

![image](https://user-images.githubusercontent.com/1328523/44418206-14b9fa00-a5bb-11e8-9fb5-e94cea4f25f2.png)
