### ISSUE TITLE
Diagonal walking on carpets broken

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#212]
I'm walking like a snake instead of diagonal.

**Comment by emansom** [comment]
Could you provide an recording of the issue and a recording of what it should look/behave like?

**Comment by Quackster** [comment]
Diagonal walking works fine. I did make it so chairs are now blocking when you try to walk through them though.

**Comment by gefliptemens** [comment]
![walking](https://user-images.githubusercontent.com/42554575/44489700-7a11f780-a65c-11e8-9e8a-ffa058bce73d.gif)

**Comment by Quackster** [comment]
Fixed: https://github.com/Quackster/Kepler/commit/c97dbc705582898c158cc12bcf69e757a3d0c4a8
