### ISSUE TITLE
Sort recommended rooms by room rating and set room rating votes to expire in a defined period of time

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#215]

**Comment by Quackster** [comment]
Wrong. The recommended rooms is based on room ratings, and the room ratings get reset every 24 hours. 

https://www.habboxforum.com/showthread.php?t=467142

**Comment by emansom** [comment]
Room ratings didn't get reset back in v21. I remember my rooms having >2K votes.

**Comment by Quackster** [comment]
This forum post was in 2008, so they must get reset. I don't know the exact interval though.

**Comment by emansom** [comment]
They didn't get reset on .nl around that time.

**Comment by Quackster** [comment]
I have forum posts from 2008 to prove that they did get reset, also it's actually just sorted by room ratings, doesn't matter if the room is active or not.

**Comment by Quackster** [comment]
https://help.habbo.com/hc/en-us/articles/221643728-What-are-room-ratings-

>Rooms ratings expire over time so this means that if there's more old ratings expiring than there are new ratings being made, the overall rating of your room will go down.  This ensures that the highest rated rooms are the rooms which are currently and consistently the most popular.

The room votes need a timestamp next to them, for when that vote expires.

**Comment by emansom** [comment]
Could be me not noticing the decrease. The room was fairly popular at the time. I suggest a TTL for the votes of a month, configurable via a GameSetting.

**Comment by emansom** [comment]
Should loop over active rooms first, and pick atleast the first entry to be the most popular active room. This would give the illusion of the hotel being semi-active.
