### ISSUE TITLE
Bathtub bug

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#217]
A very weird bug:
when you click on the second tile of a bathtub, you're supposed to go there immediately. (tested in real habbo)

So most of the times it does. But sometimes it acts like a bed: you go to the first tile. Why is this random?

![strange](https://user-images.githubusercontent.com/42554575/44633118-caec5d80-a986-11e8-8051-5b2a74a28915.gif)

**Comment by Quackster** [comment]
It's a client issue, you need to click the tile carefully underneath the bathtub or else it doesn't work, and the client sends a different walk request.

I can't do anything about this.
