### ISSUE TITLE
Pathfinding bug

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#218]
This happens in the room "Dunno" from "Igoor".

There is one unwalkable tile.

![bug](https://user-images.githubusercontent.com/42554575/44633185-beb4d000-a987-11e8-8b7a-b4bdeb607044.gif)

**Comment by Quackster** [comment]
He's probably stacked something higher than the client can see, there's no other reason why this would happen.

**Comment by Quackster** [comment]
I don't know.
