### ISSUE TITLE
Pathfinding detour

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#219]
There is something slightly different about the way Habbo and Kepler handle pathfinding.

Notice how Kepler stays closer to the borders, creating a slight unnecessary detour.

![path1](https://user-images.githubusercontent.com/42554575/44633326-3126af80-a98a-11e8-9c72-1b8cf1067c12.gif)
![path2](https://user-images.githubusercontent.com/42554575/44633327-31bf4600-a98a-11e8-8642-2590a153280d.gif)

**Comment by GuenosNoLife** [comment]
I'm not sure but I think it's normal in old, today HABBO is different...

**Comment by Quackster** [comment]
Yeah, this is something fundamental to the current pathfinder of Kepler. It's not going to be fixed.
