### ISSUE TITLE
Walking on carpet bug

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#221]
When I put a carpet first, then put ducks on top of it, everything works fine.

The problems begin when I put a carpet under ducks that already there.
For starters: in Habbo this is impossible, you have to remove the ducks first!

In Kepler, it puts the carpet under the ducks but fucks up the walking. I can walk on ducks now.

![duck2](https://user-images.githubusercontent.com/42554575/44667548-5fa09b00-aa1b-11e8-8811-d8264a07a60b.gif)

This bug is persistant when reloading the room.

**Comment by Quackster** [comment]
Fixed it, must've broken it before: https://github.com/Quackster/Kepler/commit/f0f7a378b75d25b05a99c4e9e392b11e107bacdd
