### ISSUE TITLE
Tele stack bug

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#223]
Not sure if this is normal behaviour.
I stacked a little duck on my tele.
When I teleport to it, I'm stuck on top of it.

![tele](https://user-images.githubusercontent.com/42554575/44693285-3e659c00-aa67-11e8-9473-4fe304f377ce.gif)

Furthermore, going inside the tele is broken.

![tele2](https://user-images.githubusercontent.com/42554575/44693308-635a0f00-aa67-11e8-9ba3-bc26a44c156a.gif)

**Comment by Quackster** [comment]
Definitely a bug, marking as such.
