### ISSUE TITLE
Falling from heights

### ISSUE THREAD

**Issue by gefliptemens** [Quackster/Kepler#224]
Falling from great heights does not work. Forgive me if this is suppposed to be the case :)

![falling](https://user-images.githubusercontent.com/42554575/44693452-70c3c900-aa68-11e8-8c46-147f1ce98347.gif)

**Comment by Quackster** [comment]
Yeah, seems like you're right.

https://habboblogging.wordpress.com/2013/05/13/on-walking-and-stacking/

Seems in 2013 they only changed it from being allowed to drop from extreme heights to only 1.25 tiles.

I'll extend the maximum drop height then, I guess. 😛

**Comment by gefliptemens** [comment]
Just remove the limit completely?

**Comment by Quackster** [comment]
Nah, not if Kepler wants to be multiversion in future. Also I accidentally closed the ticket, so it was a mistake. 🙄
