### ISSUE TITLE
Problem sit chair in BattleBall room

### ISSUE THREAD

**Issue by GuenosNoLife** [Quackster/Kepler#225]
![enregist _2018_08_30_00_02_22_94](https://user-images.githubusercontent.com/42077840/44818190-62042000-abe8-11e8-9e55-45642301457e.gif)

Two chair have problem

**Comment by GuenosNoLife** [comment]
I forgot too one another chair doesn't work.

![enregist _2018_09_02_20_11_56_87](https://user-images.githubusercontent.com/42077840/44959319-90397680-aeec-11e8-83ab-4664c32a3533.gif)

**Comment by JairKuma** [comment]
I can in the chair of the second image
