### ISSUE TITLE
Duplicate character after game end Battleball

### ISSUE THREAD

**Issue by GuenosNoLife** [Quackster/Kepler#226]
![enregist _2018_08_30_00_13_13_105](https://user-images.githubusercontent.com/42077840/44818617-f622b700-abe9-11e8-95d3-1e8f9b4087ad.gif)

For remove this bug, need reload room... Yes thomas is not here, he leave room.

It's appear only If I don't join a game, just stay at room lobby.

**Comment by Quackster** [comment]
Fixed: https://github.com/Quackster/Kepler/commit/762d33fbd5e9084427df977a54934110f4f49676
