### ISSUE TITLE
Teleporter bug?

### ISSUE THREAD

**Issue by Igoorx** [Quackster/Kepler#230]
I'm not really sure if this is a bug, but basically when you leave a room as soon as the teleporter door opens, you can save the state of being teleported and if you deliberately enter the room where the teleporter would teleport you, you will enter the room through the teleporter.
![proof4](https://user-images.githubusercontent.com/14041768/44951130-48eeaf80-ae32-11e8-9b28-1763bc2835e3.gif)

**Comment by gefliptemens** [comment]
Nice found
