### ISSUE TITLE
Walking on sittable furni

### ISSUE THREAD

**Issue by Igoorx** [Quackster/Kepler#231]
Possibly related to: #221 
![proof5](https://user-images.githubusercontent.com/14041768/44951247-aa644d80-ae35-11e8-9fa0-e7c1e1d24e0c.gif)

**Comment by Quackster** [comment]
Which room is this? It seems to be affected by the rug.

**Comment by Igoorx** [comment]
My room called "Dunno"

**Comment by Quackster** [comment]
Fixed, the polar bear rug and the bench just needed to be moved.
