### ISSUE TITLE
Problem with accented characters in chat

### ISSUE THREAD

**Issue by BjkGkh** [Quackster/Kepler#233]
Accented characters aren't supported in chat:

![palemoon_2018-09-07_05-17-21](https://user-images.githubusercontent.com/6693475/45196630-7afe7800-b25d-11e8-81ee-0605b8beafe4.png)

**Comment by JairKuma** [comment]
those who use windows poop (I mean windows 10) they have problems with characters like these characters and they have client down, for this reason the server is not using accented characters

**Comment by Quackster** [comment]
Accents are allowed again, some might cause disconnections but that's a shockwave issue, nothing to do with Kepler.
