### ISSUE TITLE
Impossible to put on gold bar

### ISSUE THREAD

**Issue by GuenosNoLife** [Quackster/Kepler#234]
![enregist _2018_09_09_10_54_32_284](https://user-images.githubusercontent.com/42077840/45262828-eba0c280-b41e-11e8-9443-008c6ae8aadf.gif)

Before it worked well, we could put an oriental screen too (on his left only).

EDIT: Shelf doesn't work too, if we put on roller (gold bar or shelf) It's work well. But if It's on floor It's not possible to put on.

**Comment by Quackster** [comment]
Fixed.
