### ISSUE TITLE
V26: Disconnected suddenly

### ISSUE THREAD

**Issue by ElroyNL** [Quackster/Kepler#24]
Hello,

I was in the hotel for a while, and all of a sudden I was disconnected; I did nothing to trigger this user-side because I was doing things outside the hotel. The following error were listed:

`ake room!;21.33.45 -updateProcess-Room Component Class-Attempted to remake room!;21.36.22 -getInt-Variable Container Class-Variable not found: "balloons.rightmargin";21.36.23 -eventProcUserObj-Room Interface Class-User object not found: 14541;21.37.43 -eventProcUserObj-Room Interface Class-User object not found: 11361;21.38.10 -eventProcUserObj-Room Interface Class-User object not found: 8185;21.42.09 -handle_error-Room Handler Class-Info: mod_warn/dvvd ;21.42.09 -handle_error-Navigator Handler Class-Info: mod_warn/dvvd ;21.42.09 -handleErr-Login Handler Class-Error from server: mod_warn/dvvd ;21.42.09 -create-Writer Manager Class-Writer already exists: dialog_writer_bold;22.28.42 -eventProcUserObj-Room Interface Class-User object not found: 73393;22.38.39 -getInt-Variable Container Class-Variable not found: "balloons.rightmargin";22.38.39 -eventProcUserObj-Room Interface Class-User object not found: 75853;22.44.47 -handleDisconnect-Login Handler Class-Connection was disconnected: Info;`

Thank you in advance.

**Comment by ElroyNL** [comment]
It happens another time, when browsing the catalogue:

`;23.14.44 -update-Download Instance Class-Download failed too many times:;23.14.44 -update-Download Instance Class-Download error:;23.14.44 -update-Download Instance Class-Download failed too many times:;23.14.46 -update-Download Instance Class-Download error:;23.14.46 -update-Download Instance Class-Download error:;23.14.48 -update-Download Instance Class-Download error:;23.14.48 -update-Download Instance Class-Download error:;23.14.50 -update-Download Instance Class-Download error:;23.14.50 -update-Download Instance Class-Download error:;23.14.53 -update-Download Instance Class-Download error:;23.14.53 -update-Download Instance Class-Download error:;23.14.55 -update-Download Instance Class-Download error:;23.14.55 -update-Download Instance Class-Download failed too many times:;23.14.55 -update-Download Instance Class-Download error:;23.14.55 -update-Download Instance Class-Download failed too many times:;23.15.26 -handleDisconnect-Login Handler Class-Connection was disconnected: Info;`

By the way, when opening the Space tab, it always crashes.

**Comment by Quackster** [comment]
There is no support for v26.
