### ISSUE TITLE
Walking on a HABBO

### ISSUE THREAD

**Issue by GuenosNoLife** [Quackster/Kepler#240]
Too on furni example Scoreboard but we can not redo the bug... Maybe later. (Move a furni, place and move in same time)

![enregist _2018_09_13_19_00_42_591](https://user-images.githubusercontent.com/42077840/45504506-56892b00-b78a-11e8-9cda-95fde0049682.gif)

![enregist _2018_09_13_19_01_38_673](https://user-images.githubusercontent.com/42077840/45504507-56892b00-b78a-11e8-93b8-bc2914a4fb40.gif)

**Comment by Quackster** [comment]
I don't know how to fix this, maybe pick up and place down all the furniture again.
