### ISSUE TITLE
Noob furni is tradeable

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#242]

**Comment by Quackster** [comment]
Actually they're not, as defined in the database, the problem is that trading in general allows any non-tradable item to placed into it.

![image](https://user-images.githubusercontent.com/1328523/47887988-d334ad80-de8d-11e8-8790-98ee7841b82f.png)

**Comment by emansom** [comment]
There's a flag for handitems packet to indicate non-tradeable.
