### ISSUE TITLE
V26: Trax, Spaces and achievements doesn't work

### ISSUE THREAD

**Issue by ElroyNL** [Quackster/Kepler#25]
Hello,

1. When I try to use the Trax machine, I cannot add a disc to it and therefor I am unable to make music.
2. When opening the Spaces tab in the catalogue, I will be disconnect.
3. When opening the Achievements tab in the Badges window, I will be disconnect.

Thank you in advance.

**Comment by Quackster** [comment]
Is this on the v26 client? v26 isn't officially supported, it is just a test. It only goes to v21 as maximum official support.

**Comment by ElroyNL** [comment]
> Is this on the v26 client? v26 isn't officially supported, it is just a test. It only goes to v21 as maximum official support.

Indeed, it is V26 with CMS. Could you add support for V26? Otherwise I need to stay at Holograph and that would be unfortunate...

Thank you in advance. Keep up the good work.

**Comment by Quackster** [comment]
There is no plans to support v26. I am retiring this project very soon.
