### ISSUE TITLE
V21: white dots

### ISSUE THREAD

**Issue by ElroyNL** [Quackster/Kepler#27]
Hello,

I see some white dots in the texts:

![Screenshot_190](https://user-images.githubusercontent.com/17785391/106637879-86b40d00-6583-11eb-8f97-6c21d3386177.png)

Thank you in advance.

**Comment by emansom** [comment]
Please don't report client related rendering bugs. Blame retired developers at MacroMedia and $ulake.

**Comment by ElroyNL** [comment]
@emansom bij V26 had ik dit niet. Is dit normaal bij V21?

**Comment by Jordo-o** [comment]
> @emansom bij V26 had ik dit niet. Is dit normaal bij V21?

It could be that your dcr file or one of the other server files is broken.
You can find all the files via this [link](https://alex-dev.org/archive/Habbo%20Archives/Shockwave/nodebay.com/Habbo/DCRs/).
