### ISSUE TITLE
unicode characters

### ISSUE THREAD

**Issue by cvasqxz** [Quackster/Kepler#28]
Hi, i'm trying to use the external_texts from habbo.es but the spanish characters (á, é, í, ó, ú, ü, ñ, ¿, ¡) aren't showing correctly

![imagen](https://user-images.githubusercontent.com/7388927/107703975-451a1500-6c9b-11eb-8e8c-ad8162cb295f.png)

**Comment by Jordo-o** [comment]
Looks like a problem in your shockwave player or browser.
It's definitely not a problem in the server, because the server is not handling any of these files.

Maybe you can change the external textfile and define the characters as a unicode instead of a character.
For example: `&#224; or &agrave;` instead of `à`.

**Comment by AlexandreVassard** [comment]
Hey, the solution is to download Notepad++, open your texts file and then, click in the menu at "Encoding" -> "Convert in ANSI".
This solves the solution with french texts that have special characters too.

**Comment by emansom** [comment]
> Hey, the solution is to download Notepad++, open your texts file and then, click in the menu at "Encoding" -> "Convert in ANSI".
> This solves the solution with french texts that have special characters too.

Good catch. This explains why Woodpecker [opted for ISO-8859-1/ANSI internally](https://github.com/CarlosX/Woodpecker/blob/8747b60d14e27c09822b15cfc1c89964e3cecbf5/src/Core/Configuration.cs#L70). Shockwave only supports "special" characters characters truly with ANSI, where as with UTF-8 only a subset is supported.

Further digging reveals that about two decades ago, there was some [discussion](https://macromedia.director.lingo.narkive.com/lNezaPwV/director-xml-and-russia) on the subject of UTF and ANSI mismatch within Macromedia Shockwave. They came to the conclusion that UTF-8 isn't fully supported within Shockwave. The "best" (as in being most compatible) alternative is indeed ISO-8859-1/ANSI.
