### ISSUE TITLE
CFH tickets stucks

### ISSUE THREAD

**Issue by santi134565** [Quackster/Kepler#31]
If users deletes their CFH ticket and try to make a new one they will get the avise that they have one still and if they want to delete it (but they already deleted it??) and so on, on staff clients the cfh button dissapearrs (if there arent more tickets to attend) leaving a unexistend ticket on a user side

**Comment by Quackster** [comment]
Fixed in commit https://github.com/Quackster/Kepler/commit/49cbdb5bdb66a447641622b1e27858c07e08003d
