### ISSUE TITLE
With the new pathfinding its possible to walk into the pools with clothes on.

### ISSUE THREAD

**Issue by Webbanditten** [Quackster/Kepler#32]

**Comment by Quackster** [comment]
This change isn't even put out on release yet, no reason for this ticket to open when I am fully aware of it.

**Comment by emansom** [comment]
Friendly reminder that Alex assumes everyone is a mind reader. See exhibit above as example.

**Comment by Webbanditten** [comment]
@emansom of course - I'm trying my best. 

I would have written you on Discord @Quackster but you seem to have removed me by mistake or something.

**Comment by Quackster** [comment]
My discord got hacked.

**Comment by Webbanditten** [comment]
Damn im sorry, you can add me on JUGH3AD#1212 if you feel like it.
