### ISSUE TITLE
How to run Kepler correctly

### ISSUE THREAD

**Issue by Helias** [Quackster/Kepler#4]
Hi, I'm really new here in the habbo retro server world, I know how to run Kepler.jar but I don't know hoe to access to the habno server, I visited the urls localhost:XXXX that Kepler suggest but it doesn't show anything

What I need? I need a habbo client?
Or a CMS?

**Comment by Zaikurun** [comment]
Pretty sure you need a loader, which you can find almost anywhere, just Google "habbo v18 loader". Use Pale Moon browser for Shockwave compatability. There is no compatible CMS yet.

By the way, can you post your recompiled .jar after fixing the netty problem? Gradle doesn't wanna cooperate with me.

You can add me on Discord: zaihopp#2697 if you use that

**Comment by Helias** [comment]
Here you are 😉
[Kepler-Server.zip](https://github.com/Quackster/Kepler/files/2708943/Kepler-Server.zip)

**Comment by Quackster** [comment]
There's no "URL" that Kepler suggests. It just listens on an IP and port that you provide in settings.ini.

Get a loader (use v14, not v18) and make the IP and port match.

**Comment by barbixxxa** [comment]
Im running the server, I installed the basilik, but it never shows to me in the browser. I downloaded the loader v14 by quackter and configured the ip also.

![image](https://user-images.githubusercontent.com/13052258/220401741-ae933a80-4d49-42ea-9a7d-00337e87332c.png)

![image](https://user-images.githubusercontent.com/13052258/220401834-ea487147-f104-40c3-9fda-e74853332558.png)

What do i need to do?

**Comment by barbixxxa** [comment]
I even followed this steps (https://github.com/Quackster/Kepler/blob/79e663e0bc5cd46c66f9512b51f1e978f6ae40c7/README.md), got a bit further, but its not working yet
![image](https://user-images.githubusercontent.com/13052258/220633690-ed28d98a-3673-41e5-afe3-4f6d4ea91ba2.png)
