### ISSUE TITLE
No sprites on furni

### ISSUE THREAD

**Issue by KernelPanic22** [Quackster/Kepler#49]
I managed to set up the hotel without problems but when I log in and try to buy furni all of them have no sprites on them.
Im using the v14 client.

**Comment by Webbanditten** [comment]
Your variables file probably points to the wrong directory with the furni cast files.

**Comment by KernelPanic22** [comment]
Thank you !! Had to fix the url on external_vars inside my client.

**Comment by Webbanditten** [comment]
@KernelPanic22 Remember to close the issue if it worked.
