### ISSUE TITLE
Broken furniture in the catalog

### ISSUE THREAD

**Issue by ghost** [Quackster/Kepler#66]
## Executive
![image](https://github.com/Quackster/Kepler/assets/154023155/022e6708-7891-4402-a3fb-6d42516bc61a)

## Missing gold trophy
![image](https://github.com/Quackster/Kepler/assets/154023155/dbe8d26b-0451-4b0c-8975-375ce21ad637)

**Comment by Quackster** [comment]
Not broken, Executive as a line didn't exist when Habbo v14 was around.
