### ISSUE TITLE
Como adciono mobs no catalogo Kepler(PT BR) // How to add background in the kepler emulator catalog? (EN-US) *Translate Google

### ISSUE THREAD

**Issue by MandelaHP** [Quackster/Kepler#67]
Como adciono mobs no catalogo Kepler(PT BR) // How to add background in the kepler emulator catalog? (EN-US) *Translate Google

Por Favor me ajuda! (PT BR)

Please my help! (EN US)

Obrigado por seu suporte de emulador, ele é muito  bom servidor de emulador! (PT BR)
Thanks for you suport emulator, he is very good emulator server! (en us)

**Comment by Webbanditten** [comment]
This issue seems unrelated to the Kepler server which this repository contains. I suggest you submit your ask for help on client specific topics on https://forum.oldskooler.org/ or Ragezone.

**Comment by Quackster** [comment]
GitHub tickets are for reporting issues, not support.
