### ISSUE TITLE
Which .cct/.cst file controls the pocket?

### ISSUE THREAD

**Issue by tiomurray** [Quackster/Kepler#69]
I need to know which .cct or .cst file controls the opening of windows like pocket or catalogue, as I need to change the coordinates in which the window is opened.

**Comment by Webbanditten** [comment]
This issue seems unrelated to the Kepler server which this repository contains. I suggest you submit your ask for help on client specific topics on https://forum.oldskooler.org/ or Ragezone.

**Comment by Quackster** [comment]
GitHub tickets are for reporting issues, not support.
