### ISSUE TITLE
Feature: Moderation tools

### ISSUE THREAD

**Issue by Quackster** [Quackster/Kepler#71]

**Comment by emansom** [comment]
@Raptosaur is working on this in his Kepler fork on the `develop` branch.

**Comment by Raptosaur** [comment]
Kick User, Alert User, Room Alert and Room Kick all working. Just need to implement Banning.
![kick](https://user-images.githubusercontent.com/7223575/43356322-0e73d06e-925e-11e8-8925-f03eefa5ce0d.png)

**Comment by Quackster** [comment]
Banning still needs to be done.
