### ISSUE TITLE
Calculation of HC days are not accurate when subscribing

### ISSUE THREAD

**Issue by Quackster** [Quackster/Kepler#73]
Club month subscribed count needs to be redone, as the calculation does not factor in months in between of not being subscribed.

**Comment by emansom** [comment]
I propose changing the `club_subscribed` column in the `users` table to instead hold a duration value (in seconds) of the total sum of club subscription time.

**Comment by emansom** [comment]
@romualdr feeback?

**Comment by Quackster** [comment]
Your proposal is unrelated to the bug.

**Comment by Quackster** [comment]
This has pretty much taken care of itself by using ``club_subscribed``
