### ISSUE TITLE
Sometimes Kepler stops processing packets seemingly randomly

### ISSUE THREAD

**Issue by Quackster** [Quackster/Kepler#84]
This issue isn't easily reproducible at the moment.

**Comment by Quackster** [comment]
Currently investigating whether or not https://github.com/Quackster/Kepler/commit/6320539e0a8319d689a4e7f8db3a48988951c6e8 will fix the issue, as I believe maybe Netty will handle it better if I chose not to override it.

**Comment by emansom** [comment]
Still seems to happen from time to time. Last time it happened was when stacking furniture.

**Comment by emansom** [comment]
Last packet processed before the full stop is SSO

**Comment by emansom** [comment]
Still happens. Last packet received was SSO. We were in the HFB game room with multiple users.

```2018-07-22T18:42:40.382 INFO  [Connection 7] - Received (SSO): 204 / CL@`UnlXVjlUMFFDNjlFMW4rYVBmT0RLUT09```

**Comment by Sefhriloff** [comment]
before the kepler frezze all players cant walk in rooms but can talk,etc
after 15-20 seconds kepler frezze

**Comment by emansom** [comment]
Happened three times in a row in the HFB game room. I think something may be wrong with the collision map / room map.

**Comment by Quackster** [comment]
The bug seems to have vanished, closing the ticket (for now). The following commits probably fixed it;

- https://github.com/emansom/Kepler/commit/6f61387d678626c6fb866aff5c1da0a879293fe5

- https://github.com/Quackster/Kepler/commit/501a63a8f82ac71f169b53e28dc98b5275703421

- https://github.com/Quackster/Kepler/commit/8818c9c962c6754e96cd0a2b28da5099bffa7111

- https://github.com/Quackster/Kepler/commit/a204105f3704e5a98129a5c115e25cc599b0d691

**Comment by Quackster** [comment]
Bug happened again, seeing if this commit (https://github.com/Quackster/Kepler/commit/28adacdd0f3c9c4baba3ad6dd0dd42f5b7a688c1) will fix it.

**Comment by Quackster** [comment]
Nope, but the thread dumps look like the database is locking up. I've pushed some optimisations to use less database connections, particularly circulating around the console and grabbing details. (re https://github.com/Quackster/Kepler/commit/6cac499df6992015bd54b36a26923610e57166e8 https://github.com/Quackster/Kepler/commit/36b3ff8a52212888c23f3a63b39bcffb58b408e5).

VisualVM analysis of the thread dump shows a lot of these: 

![image](https://user-images.githubusercontent.com/1328523/43236277-841855c6-90c7-11e8-9721-a6b14a1b2185.png)

Testing if the following commits on the develop branch has fixed the issue.

**Comment by Quackster** [comment]
10 hours uptime on oldHabbo so far with 6+ users, looking good! 👍

**Comment by Quackster** [comment]
Almost 2 days with no freezing whatsoever! 🙌 I was asleep during peakhours, how many were online?

![image](https://user-images.githubusercontent.com/1328523/43353115-5c3f6b4a-9273-11e8-98a0-ce557d1c454e.png)

**Comment by emansom** [comment]
Max I counted was 4. It was a hectic workday, thus wasn't online much.

**Comment by Quackster** [comment]
I'm going to assume it's been fixed, with the latest changes to the DAO's and how the messenger is loaded.
