### ISSUE TITLE
Cannot choose a room category!

### ISSUE THREAD

**Issue by Gibbozz** [Quackster/Kepler#9]
Hello, I am having an issue with Kepler on V15. When creating rooms, you cannot choose a category for the room to go under. Will not let you click on any.
![test](https://user-images.githubusercontent.com/60108829/72744842-41a28000-3ba6-11ea-8034-5d161faeae57.png)

**Comment by Quackster** [comment]
This is *also* certainly a DCR issue. I've posted the DCR pack I've used for Kepler on the main thread.
