### ISSUE TITLE
Several furni and furni lines from catalogue missing

### ISSUE THREAD

**Issue by emansom** [Quackster/Kepler#97]

**Comment by Quackster** [comment]
Please elaborate instead of being vague on the issue, mention which furni lines, etc.

**Comment by emansom** [comment]
On the Teleporters page, the Door Teleport is missing. Likely a new layout for the page is needed too.

![Teleporter catalogue page in Kepler](https://images.oldhabbo.com/catalogue_teleporters_page_kepler.png)
Currently in Kepler it looks like this
 
![Teleporter catalogue page in 2008](https://images.oldhabbo.com/teleporters_2008.png)
It should look like this instead
